version: "3.9"

services:
  # ----- ZooKeeper -----
  zookeeper:
    image: bitnami/zookeeper:3.9          # 輕量版，免自行安裝 Java
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes         # 開發環境先不設帳密
    ports:
      - "2181:2181"                       # 主機→容器

  # ----- Kafka Broker -----
  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    depends_on:
      - zookeeper                         # 先等 ZooKeeper 完成
    environment:
      - KAFKA_BROKER_ID=${KAFKA_BROKER_ID}
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_ADVERTISED_HOST_NAME}:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka         # Topic 與 log 存這裡

  # ----- PostgreSQL -----
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "15432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data  # DB 持久化

volumes:
  kafka_data:
  pg_data:
